### ISSUE TITLE
你的输入法皮肤叫啥名字，能分享下不

### ISSUE THREAD

**Issue by shaGuar-svg** [elecV2/ubmusic-docker#1]
你的输入法皮肤叫啥名字，能分享下不

**Comment by elecV2** [comment]
百度输入法皮肤 aries + 自改。这是一款收费皮肤，就不分享了。

**Comment by shaGuar-svg** [comment]
谢谢，已购了，请问下你自改了哪些地方

**Comment by elecV2** [comment]
差不多一年前改的了，中间根据自己的使用情况又陆陆续续修改些，具体改了啥，我也说不清楚。而且我也不知道最新的aries 有哪些变化，所以你只能对照一下图片找不同了。
首先，键盘布局是重构了，自制的13键。

> 谢谢，已购了，请问下你自改了哪些地方
